[build]
  command = "npm run build"
  publish = "_site"
  functions = "src/functions"
  NODE_ENV = "19.5.0"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200